#!/bin/bash

set -v

# (re)create empty DB

dropdb gyn 
sudo -u postgres dropuser $USER 
sudo -u postgres createuser -d $USER
createdb gyn

# create tables

pushd "$(dirname "$(readlink -f "$BASH_SOURCE[0]")")" > /dev/null && {
  psql -d gyn -f ./create-tables.sql
  popd > /dev/null
}
