// Generated with genorm. DO NOT EDIT.
package pg

import (
	"database/sql"
	"github.com/austinov/gyn/backend/store"
	"time"
)

const (
	selectAppointmentByIdSql     = "SELECT id, created_at, updated_at, date_receipt, doctor_id, patient_id, receipt_kind_id, receipt_diagnosis, alergo, contact_infected, hiv, transfusion, dyscountry, smoking, drugs, inheritance, gyndiseases, paritet, paritet_b, paritet_p, paritet_a, paritet_sv, paritet_nb, paritet_eb, infection_markers_state_id, infection_markers_desc, tromboflebia_state_id, tromboflebia_desc, first_trimester, second_trimester, third_trimester, history, oprv, oprv_state_id, exp_by_menstruation, exp_by_first_visit, exp_by_ultra_first, exp_by_ultra_second, exp_by_ultra_third, health_state_id, claims, head, vision, skin_state_id, lymph, breath_state_id, rale_state_id, tones_state_id, pulse, pulse_type, pressure, tongue_clean, tongue_wet, tongue_dry, tongue_coated, tongue_uncoated, throat, belly_period, belly_state_id, epigastrium_state_use, epigastrium_state_id, scar_state_use, scar_state_id, peritoneal, labors, dysuric, bowel, limb_swelling, uteruse_state_id, fetal_position_id, fetal_previa_id, fetal_align_id, fetal_heartbeat_id, heartbeat_rithm_id, fetal_pulse, reproductive_discharge_type_id, reproductive_discharge_state_id, vdm, oj, dspin, dcrist, dtroch, cext, devel_organs_id, genital_anomalies, vagina_state_id, bishop, fetal_bladder_state_id, fetal_bladder_previa_id, fetal_bladder_align_id, arches, conjugate, pelvis_state_id, pelvis_exostosis, pelvis_discharge_type_id, pelvis_discharge_state_id, diagnosis, conclusion, birth_plan_use, birth_plan FROM appointments WHERE id = $1"
	insertAppointmentSql         = "INSERT INTO appointments ( created_at, date_receipt, doctor_id, patient_id, receipt_kind_id, receipt_diagnosis, alergo, contact_infected, hiv, transfusion, dyscountry, smoking, drugs, inheritance, gyndiseases, paritet, paritet_b, paritet_p, paritet_a, paritet_sv, paritet_nb, paritet_eb, infection_markers_state_id, infection_markers_desc, tromboflebia_state_id, tromboflebia_desc, first_trimester, second_trimester, third_trimester, history, oprv, oprv_state_id, exp_by_menstruation, exp_by_first_visit, exp_by_ultra_first, exp_by_ultra_second, exp_by_ultra_third, health_state_id, claims, head, vision, skin_state_id, lymph, breath_state_id, rale_state_id, tones_state_id, pulse, pulse_type, pressure, tongue_clean, tongue_wet, tongue_dry, tongue_coated, tongue_uncoated, throat, belly_period, belly_state_id, epigastrium_state_use, epigastrium_state_id, scar_state_use, scar_state_id, peritoneal, labors, dysuric, bowel, limb_swelling, uteruse_state_id, fetal_position_id, fetal_previa_id, fetal_align_id, fetal_heartbeat_id, heartbeat_rithm_id, fetal_pulse, reproductive_discharge_type_id, reproductive_discharge_state_id, vdm, oj, dspin, dcrist, dtroch, cext, devel_organs_id, genital_anomalies, vagina_state_id, bishop, fetal_bladder_state_id, fetal_bladder_previa_id, fetal_bladder_align_id, arches, conjugate, pelvis_state_id, pelvis_exostosis, pelvis_discharge_type_id, pelvis_discharge_state_id, diagnosis, conclusion, birth_plan_use, birth_plan ) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, $91, $92, $93, $94, $95, $96, $97, $98 ) RETURNING id"
	updateAppointmentSql         = "WITH rows AS (UPDATE appointments SET updated_at = $1, date_receipt = $2, doctor_id = $3, patient_id = $4, receipt_kind_id = $5, receipt_diagnosis = $6, alergo = $7, contact_infected = $8, hiv = $9, transfusion = $10, dyscountry = $11, smoking = $12, drugs = $13, inheritance = $14, gyndiseases = $15, paritet = $16, paritet_b = $17, paritet_p = $18, paritet_a = $19, paritet_sv = $20, paritet_nb = $21, paritet_eb = $22, infection_markers_state_id = $23, infection_markers_desc = $24, tromboflebia_state_id = $25, tromboflebia_desc = $26, first_trimester = $27, second_trimester = $28, third_trimester = $29, history = $30, oprv = $31, oprv_state_id = $32, exp_by_menstruation = $33, exp_by_first_visit = $34, exp_by_ultra_first = $35, exp_by_ultra_second = $36, exp_by_ultra_third = $37, health_state_id = $38, claims = $39, head = $40, vision = $41, skin_state_id = $42, lymph = $43, breath_state_id = $44, rale_state_id = $45, tones_state_id = $46, pulse = $47, pulse_type = $48, pressure = $49, tongue_clean = $50, tongue_wet = $51, tongue_dry = $52, tongue_coated = $53, tongue_uncoated = $54, throat = $55, belly_period = $56, belly_state_id = $57, epigastrium_state_use = $58, epigastrium_state_id = $59, scar_state_use = $60, scar_state_id = $61, peritoneal = $62, labors = $63, dysuric = $64, bowel = $65, limb_swelling = $66, uteruse_state_id = $67, fetal_position_id = $68, fetal_previa_id = $69, fetal_align_id = $70, fetal_heartbeat_id = $71, heartbeat_rithm_id = $72, fetal_pulse = $73, reproductive_discharge_type_id = $74, reproductive_discharge_state_id = $75, vdm = $76, oj = $77, dspin = $78, dcrist = $79, dtroch = $80, cext = $81, devel_organs_id = $82, genital_anomalies = $83, vagina_state_id = $84, bishop = $85, fetal_bladder_state_id = $86, fetal_bladder_previa_id = $87, fetal_bladder_align_id = $88, arches = $89, conjugate = $90, pelvis_state_id = $91, pelvis_exostosis = $92, pelvis_discharge_type_id = $93, pelvis_discharge_state_id = $94, diagnosis = $95, conclusion = $96, birth_plan_use = $97, birth_plan = $98 WHERE id = $99 RETURNING 1) SELECT count(*) FROM rows"
	selectAppointmentViewByIdSql = "SELECT id, created_at, updated_at, date_receipt, doctor_id, patient_id, receipt_kind_id, receipt_diagnosis, alergo, contact_infected, hiv, transfusion, dyscountry, smoking, drugs, inheritance, gyndiseases, paritet, paritet_b, paritet_p, paritet_a, paritet_sv, paritet_nb, paritet_eb, infection_markers_state_id, infection_markers_desc, tromboflebia_state_id, tromboflebia_desc, first_trimester, second_trimester, third_trimester, history, oprv, oprv_state_id, exp_by_menstruation, exp_by_first_visit, exp_by_ultra_first, exp_by_ultra_second, exp_by_ultra_third, health_state_id, claims, head, vision, skin_state_id, lymph, breath_state_id, rale_state_id, tones_state_id, pulse, pulse_type, pressure, tongue_clean, tongue_wet, tongue_dry, tongue_coated, tongue_uncoated, throat, belly_period, belly_state_id, epigastrium_state_use, epigastrium_state_id, scar_state_use, scar_state_id, peritoneal, labors, dysuric, bowel, limb_swelling, uteruse_state_id, fetal_position_id, fetal_previa_id, fetal_align_id, fetal_heartbeat_id, heartbeat_rithm_id, fetal_pulse, reproductive_discharge_type_id, reproductive_discharge_state_id, vdm, oj, dspin, dcrist, dtroch, cext, devel_organs_id, genital_anomalies, vagina_state_id, bishop, fetal_bladder_state_id, fetal_bladder_previa_id, fetal_bladder_align_id, arches, conjugate, pelvis_state_id, pelvis_exostosis, pelvis_discharge_type_id, pelvis_discharge_state_id, diagnosis, conclusion, birth_plan_use, birth_plan, doctor_name, patient_name, receipt_kind_name, infection_markers_state_name, tromboflebia_state_name, oprv_state_name, health_state_name, skin_state_name, breath_state_name, rale_state_name, tones_state_name, belly_state_name, epigastrium_state_name, scar_state_name, uteruse_state_name, fetal_position_name, fetal_previa_name, fetal_align_name, fetal_heartbeat_name, heartbeat_rithm_name, reproductive_discharge_type_name, reproductive_discharge_state_name, devel_organs_name, vagina_state_name, fetal_bladder_state_name, fetal_bladder_previa_name, fetal_bladder_align_name, pelvis_state_name, pelvis_discharge_type_name, pelvis_discharge_state_name FROM vw_appointments WHERE id = $1"
)

var (
	selectAppointmentByIdStmt     *sql.Stmt
	insertAppointmentStmt         *sql.Stmt
	updateAppointmentStmt         *sql.Stmt
	selectAppointmentViewByIdStmt *sql.Stmt
)

func getAppointmentById(id int64) (store.Appointment, error) {
	t := store.Appointment{}
	var (
		CreatedAt sql.NullInt64
		UpdatedAt sql.NullInt64
	)
	err := selectAppointmentByIdStmt.QueryRow(id).Scan(
		&t.Id,
		&CreatedAt,
		&UpdatedAt,
		&t.DateReceipt,
		&t.DoctorId,
		&t.PatientId,
		&t.ReceiptKindId,
		&t.ReceiptDiagnosis,
		&t.Alergo,
		&t.ContactInfected,
		&t.Hiv,
		&t.Transfusion,
		&t.Dyscountry,
		&t.Smoking,
		&t.Drugs,
		&t.Inheritance,
		&t.Gyndiseases,
		&t.Paritet,
		&t.ParitetB,
		&t.ParitetP,
		&t.ParitetA,
		&t.ParitetSV,
		&t.ParitetNB,
		&t.ParitetEB,
		&t.InfectionMarkersStateId,
		&t.InfectionMarkersDesc,
		&t.TromboflebiaStateId,
		&t.TromboflebiaDesc,
		&t.FirstTrimester,
		&t.SecondTrimester,
		&t.ThirdTrimester,
		&t.History,
		&t.Oprv,
		&t.OprvStateId,
		&t.ExpByMenstruation,
		&t.ExpByFirstVisit,
		&t.ExpByUltraFirst,
		&t.ExpByUltraSecond,
		&t.ExpByUltraThird,
		&t.HealthStateId,
		&t.Claims,
		&t.Head,
		&t.Vision,
		&t.SkinStateId,
		&t.Lymph,
		&t.BreathStateId,
		&t.RaleStateId,
		&t.TonesStateId,
		&t.Pulse,
		&t.PulseType,
		&t.Pressure,
		&t.TongueClean,
		&t.TongueWet,
		&t.TongueDry,
		&t.TongueCoated,
		&t.TongueUncoated,
		&t.Throat,
		&t.BellyPeriod,
		&t.BellyStateId,
		&t.EpigastriumStateUse,
		&t.EpigastriumStateId,
		&t.ScarStateUse,
		&t.ScarStateId,
		&t.Peritoneal,
		&t.Labors,
		&t.Dysuric,
		&t.Bowel,
		&t.LimbSwelling,
		&t.UteruseStateId,
		&t.FetalPositionId,
		&t.FetalPreviaId,
		&t.FetalAlignId,
		&t.FetalHeartbeatId,
		&t.HeartbeatRithmId,
		&t.FetalPulse,
		&t.ReproductiveDischargeTypeId,
		&t.ReproductiveDischargeStateId,
		&t.Vdm,
		&t.Oj,
		&t.Dspin,
		&t.Dcrist,
		&t.Dtroch,
		&t.Cext,
		&t.DevelOrgansId,
		&t.GenitalAnomalies,
		&t.VaginaStateId,
		&t.Bishop,
		&t.FetalBladderStateId,
		&t.FetalBladderPreviaId,
		&t.FetalBladderAlignId,
		&t.Arches,
		&t.Conjugate,
		&t.PelvisStateId,
		&t.PelvisExostosis,
		&t.PelvisDischargeTypeId,
		&t.PelvisDischargeStateId,
		&t.Diagnosis,
		&t.Conclusion,
		&t.BirthPlanUse,
		&t.BirthPlan)
	if err != nil {
		return t, err
	}
	if CreatedAt.Valid {
		t.CreatedAt = CreatedAt.Int64
	}
	if UpdatedAt.Valid {
		t.UpdatedAt = UpdatedAt.Int64
	}

	return t, nil
}

func insertAppointment(tx *sql.Tx, t *store.Appointment) error {
	row := tx.Stmt(insertAppointmentStmt).QueryRow(
		time.Now().Unix(),
		t.DateReceipt,
		t.DoctorId,
		t.PatientId,
		t.ReceiptKindId,
		t.ReceiptDiagnosis,
		t.Alergo,
		t.ContactInfected,
		t.Hiv,
		t.Transfusion,
		t.Dyscountry,
		t.Smoking,
		t.Drugs,
		t.Inheritance,
		t.Gyndiseases,
		t.Paritet,
		t.ParitetB,
		t.ParitetP,
		t.ParitetA,
		t.ParitetSV,
		t.ParitetNB,
		t.ParitetEB,
		t.InfectionMarkersStateId,
		t.InfectionMarkersDesc,
		t.TromboflebiaStateId,
		t.TromboflebiaDesc,
		t.FirstTrimester,
		t.SecondTrimester,
		t.ThirdTrimester,
		t.History,
		t.Oprv,
		t.OprvStateId,
		t.ExpByMenstruation,
		t.ExpByFirstVisit,
		t.ExpByUltraFirst,
		t.ExpByUltraSecond,
		t.ExpByUltraThird,
		t.HealthStateId,
		t.Claims,
		t.Head,
		t.Vision,
		t.SkinStateId,
		t.Lymph,
		t.BreathStateId,
		t.RaleStateId,
		t.TonesStateId,
		t.Pulse,
		t.PulseType,
		t.Pressure,
		t.TongueClean,
		t.TongueWet,
		t.TongueDry,
		t.TongueCoated,
		t.TongueUncoated,
		t.Throat,
		t.BellyPeriod,
		t.BellyStateId,
		t.EpigastriumStateUse,
		t.EpigastriumStateId,
		t.ScarStateUse,
		t.ScarStateId,
		t.Peritoneal,
		t.Labors,
		t.Dysuric,
		t.Bowel,
		t.LimbSwelling,
		t.UteruseStateId,
		t.FetalPositionId,
		t.FetalPreviaId,
		t.FetalAlignId,
		t.FetalHeartbeatId,
		t.HeartbeatRithmId,
		t.FetalPulse,
		t.ReproductiveDischargeTypeId,
		t.ReproductiveDischargeStateId,
		t.Vdm,
		t.Oj,
		t.Dspin,
		t.Dcrist,
		t.Dtroch,
		t.Cext,
		t.DevelOrgansId,
		t.GenitalAnomalies,
		t.VaginaStateId,
		t.Bishop,
		t.FetalBladderStateId,
		t.FetalBladderPreviaId,
		t.FetalBladderAlignId,
		t.Arches,
		t.Conjugate,
		t.PelvisStateId,
		t.PelvisExostosis,
		t.PelvisDischargeTypeId,
		t.PelvisDischargeStateId,
		t.Diagnosis,
		t.Conclusion,
		t.BirthPlanUse,
		t.BirthPlan)
	return row.Scan(&t.Id)
}

func updateAppointment(tx *sql.Tx, t *store.Appointment) (int, error) {
	row := tx.Stmt(updateAppointmentStmt).QueryRow(
		time.Now().Unix(),
		t.DateReceipt,
		t.DoctorId,
		t.PatientId,
		t.ReceiptKindId,
		t.ReceiptDiagnosis,
		t.Alergo,
		t.ContactInfected,
		t.Hiv,
		t.Transfusion,
		t.Dyscountry,
		t.Smoking,
		t.Drugs,
		t.Inheritance,
		t.Gyndiseases,
		t.Paritet,
		t.ParitetB,
		t.ParitetP,
		t.ParitetA,
		t.ParitetSV,
		t.ParitetNB,
		t.ParitetEB,
		t.InfectionMarkersStateId,
		t.InfectionMarkersDesc,
		t.TromboflebiaStateId,
		t.TromboflebiaDesc,
		t.FirstTrimester,
		t.SecondTrimester,
		t.ThirdTrimester,
		t.History,
		t.Oprv,
		t.OprvStateId,
		t.ExpByMenstruation,
		t.ExpByFirstVisit,
		t.ExpByUltraFirst,
		t.ExpByUltraSecond,
		t.ExpByUltraThird,
		t.HealthStateId,
		t.Claims,
		t.Head,
		t.Vision,
		t.SkinStateId,
		t.Lymph,
		t.BreathStateId,
		t.RaleStateId,
		t.TonesStateId,
		t.Pulse,
		t.PulseType,
		t.Pressure,
		t.TongueClean,
		t.TongueWet,
		t.TongueDry,
		t.TongueCoated,
		t.TongueUncoated,
		t.Throat,
		t.BellyPeriod,
		t.BellyStateId,
		t.EpigastriumStateUse,
		t.EpigastriumStateId,
		t.ScarStateUse,
		t.ScarStateId,
		t.Peritoneal,
		t.Labors,
		t.Dysuric,
		t.Bowel,
		t.LimbSwelling,
		t.UteruseStateId,
		t.FetalPositionId,
		t.FetalPreviaId,
		t.FetalAlignId,
		t.FetalHeartbeatId,
		t.HeartbeatRithmId,
		t.FetalPulse,
		t.ReproductiveDischargeTypeId,
		t.ReproductiveDischargeStateId,
		t.Vdm,
		t.Oj,
		t.Dspin,
		t.Dcrist,
		t.Dtroch,
		t.Cext,
		t.DevelOrgansId,
		t.GenitalAnomalies,
		t.VaginaStateId,
		t.Bishop,
		t.FetalBladderStateId,
		t.FetalBladderPreviaId,
		t.FetalBladderAlignId,
		t.Arches,
		t.Conjugate,
		t.PelvisStateId,
		t.PelvisExostosis,
		t.PelvisDischargeTypeId,
		t.PelvisDischargeStateId,
		t.Diagnosis,
		t.Conclusion,
		t.BirthPlanUse,
		t.BirthPlan,
		t.Id)
	var cnt int
	if err := row.Scan(&cnt); err != nil {
		return 0, err
	}
	return cnt, nil
}
func getAppointmentViewById(id int64) (store.AppointmentView, error) {
	t := store.AppointmentView{}
	var (
		CreatedAt sql.NullInt64
		UpdatedAt sql.NullInt64
	)
	err := selectAppointmentViewByIdStmt.QueryRow(id).Scan(
		&t.Id,
		&CreatedAt,
		&UpdatedAt,
		&t.DateReceipt,
		&t.DoctorId,
		&t.PatientId,
		&t.ReceiptKindId,
		&t.ReceiptDiagnosis,
		&t.Alergo,
		&t.ContactInfected,
		&t.Hiv,
		&t.Transfusion,
		&t.Dyscountry,
		&t.Smoking,
		&t.Drugs,
		&t.Inheritance,
		&t.Gyndiseases,
		&t.Paritet,
		&t.ParitetB,
		&t.ParitetP,
		&t.ParitetA,
		&t.ParitetSV,
		&t.ParitetNB,
		&t.ParitetEB,
		&t.InfectionMarkersStateId,
		&t.InfectionMarkersDesc,
		&t.TromboflebiaStateId,
		&t.TromboflebiaDesc,
		&t.FirstTrimester,
		&t.SecondTrimester,
		&t.ThirdTrimester,
		&t.History,
		&t.Oprv,
		&t.OprvStateId,
		&t.ExpByMenstruation,
		&t.ExpByFirstVisit,
		&t.ExpByUltraFirst,
		&t.ExpByUltraSecond,
		&t.ExpByUltraThird,
		&t.HealthStateId,
		&t.Claims,
		&t.Head,
		&t.Vision,
		&t.SkinStateId,
		&t.Lymph,
		&t.BreathStateId,
		&t.RaleStateId,
		&t.TonesStateId,
		&t.Pulse,
		&t.PulseType,
		&t.Pressure,
		&t.TongueClean,
		&t.TongueWet,
		&t.TongueDry,
		&t.TongueCoated,
		&t.TongueUncoated,
		&t.Throat,
		&t.BellyPeriod,
		&t.BellyStateId,
		&t.EpigastriumStateUse,
		&t.EpigastriumStateId,
		&t.ScarStateUse,
		&t.ScarStateId,
		&t.Peritoneal,
		&t.Labors,
		&t.Dysuric,
		&t.Bowel,
		&t.LimbSwelling,
		&t.UteruseStateId,
		&t.FetalPositionId,
		&t.FetalPreviaId,
		&t.FetalAlignId,
		&t.FetalHeartbeatId,
		&t.HeartbeatRithmId,
		&t.FetalPulse,
		&t.ReproductiveDischargeTypeId,
		&t.ReproductiveDischargeStateId,
		&t.Vdm,
		&t.Oj,
		&t.Dspin,
		&t.Dcrist,
		&t.Dtroch,
		&t.Cext,
		&t.DevelOrgansId,
		&t.GenitalAnomalies,
		&t.VaginaStateId,
		&t.Bishop,
		&t.FetalBladderStateId,
		&t.FetalBladderPreviaId,
		&t.FetalBladderAlignId,
		&t.Arches,
		&t.Conjugate,
		&t.PelvisStateId,
		&t.PelvisExostosis,
		&t.PelvisDischargeTypeId,
		&t.PelvisDischargeStateId,
		&t.Diagnosis,
		&t.Conclusion,
		&t.BirthPlanUse,
		&t.BirthPlan,
		&t.DoctorName,
		&t.PatientName,
		&t.ReceiptKindName,
		&t.InfectionMarkersStateName,
		&t.TromboflebiaStateName,
		&t.OprvStateName,
		&t.HealthStateName,
		&t.SkinStateName,
		&t.BreathStateName,
		&t.RaleStateName,
		&t.TonesStateName,
		&t.BellyStateName,
		&t.EpigastriumStateName,
		&t.ScarStateName,
		&t.UteruseStateName,
		&t.FetalPositionName,
		&t.FetalPreviaName,
		&t.FetalAlignName,
		&t.FetalHeartbeatName,
		&t.HeartbeatRithmName,
		&t.ReproductiveDischargeTypeName,
		&t.ReproductiveDischargeStateName,
		&t.DevelOrgansName,
		&t.VaginaStateName,
		&t.FetalBladderStateName,
		&t.FetalBladderPreviaName,
		&t.FetalBladderAlignName,
		&t.PelvisStateName,
		&t.PelvisDischargeTypeName,
		&t.PelvisDischargeStateName)
	if err != nil {
		return t, err
	}
	if CreatedAt.Valid {
		t.CreatedAt = CreatedAt.Int64
	}
	if UpdatedAt.Valid {
		t.UpdatedAt = UpdatedAt.Int64
	}

	return t, nil
}
